import { NombreProvider } from './context/NombreContext'; // Importa el NombreProvider
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Envuelve toda la aplicación con NombreProvider para que el contexto esté disponible */}
        <NombreProvider>
          {/* El Menu debe estar dentro del provider, para poder acceder al contexto */}
          {/* Aquí se renderiza el contenido de la página */}
          {children}
        </NombreProvider>
      </body>
    </html>
  );
}
